### ISSUE TITLE
Error occuring when trying to open main window to change Blackwidow V3 custom colours

### ISSUE THREAD

**Issue by pinkapoppy** [1kc/razer-macos#288]
An error message appears when I attempt to choose Blackwidow V3 to customise in the main window:

**A JavaScript error occured in the main process**

Uncaught Exception:
Error: Failed to serialize arguments
at Object.send (electron/js2c/browser_init.js:157:2201)
at application_Application.showView (/Applications/Razer macOS.app/Contents/Resources/app.asar/webpack:/src/main/application.js:189:36)
at originalClick (/Applications/Razer macOS.app/Contents/Resources/app.asar/webpack:/src/main/menu/menubuilderdevice.js:45:19)
at e.click (/Applications/Razer macOS.app/Contents/Resources/app.asar/webpack:/src/main/menu/menubuilder.js:19:9)
at MenuItem.click (electron/js2c/browser_init.js:73:1683)
at Object.a._executeCommand (electron/js2c/browser_init.js:81:2343)

**Comment by dhobi** [comment]
Could you try the following for me:
1. Menu -> Clear all settings (Yes)
2. Restart razer-macos

Does the error still happen?

**Comment by Suma-xy** [comment]
@pinkapoppy I also had the same error. The problem was solved after I restarted my Mac.

**Comment by dhobi** [comment]
This error happens only when the ripple animation has been activated once.

https://github.com/1kc/razer-macos/commit/c1fd43cfaa49e271546a539ac6313753bc44a27a should fix this.

**Comment by 1kc** [comment]
Cheers Daniel, I will release his later today.

**Comment by dhobi** [comment]
This should be fixed now with the latest release 0.3.8. Please reopen if it's still not working for you.
