### ISSUE TITLE
Problem building dist on mac Big Sur 11.6.5

### ISSUE THREAD

**Issue by pablocael** [1kc/razer-macos#621]
Hi there, first of all thanks for this great project.

I was trying to build the dist in Mac OS Big Sur 11.6.5 and I got the following error:

```
yarn dist

  ⨯ fs.rm is not a function  failedTask=build stackTrace=TypeError: fs.rm is not a function
    at MacPackager.doPack (/Users/pablo.elias/code/mac-setup-packages/razer-macos/node_modules/app-builder-lib/src/macPackager.ts:131:18)
    at MacPackager.pack (/Users/pablo.elias/code/mac-setup-packages/razer-macos/node_modules/app-builder-lib/src/macPackager.ts:177:7)
    at Packager.doBuild (/Users/pablo.elias/code/mac-setup-packages/razer-macos/node_modules/app-builder-lib/src/packager.ts:441:9)
    at Object.executeFinally (/Users/pablo.elias/code/mac-setup-packages/razer-macos/node_modules/builder-util/src/promise.ts:12:14)
    at Packager._build (/Users/pablo.elias/code/mac-setup-packages/razer-macos/node_modules/app-builder-lib/src/packager.ts:376:31)
    at Packager.build (/Users/pablo.elias/code/mac-setup-packages/razer-macos/node_modules/app-builder-lib/src/packager.ts:337:12)
    at Object.executeFinally (/Users/pablo.elias/code/mac-setup-packages/razer-macos/node_modules/builder-util/src/promise.ts:12:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

The full error log is here: 
[output.log](https://github.com/1kc/razer-macos/files/8503535/output.log)

Thank you

**Comment by pablocael** [comment]
UPDATE: after upgrading node, the error has changed now:
[output.log](https://github.com/1kc/razer-macos/files/8510226/output.log)

Its something about electron build.
